### ISSUE TITLE
UnreservedConcurrentExecution below its minimum value of [10]

### ISSUE THREAD

**Issue by AlexFridman** [aws-samples/amazon-rekognition-serverless-large-scale-image-and-video-processing#6]
Stack Deployments Failed: Error: The stack named RekognitionPipelineStack failed creation, it may need to be manually deleted from the AWS console: ROLLBACK_COMPLETE: Resource handler returned message: "Specified ReservedConcurrentExecutions for function decreases account's UnreservedConcurrentExecution below its minimum value of [10]. (Service: Lambda, Status Code: 400, Request ID: 4719094a-f0a2-4164-b8c4-79504bae927f)" (RequestToken: f23707e9-d033-0713-cfc7-bde20b7fc69f, HandlerErrorCode: InvalidRequest)

Hi! Could you please advise how to overcome this error?
What limit/quota increase I have to ask?

Thanks in advance.

**Comment by hammzagee** [comment]
Hi there,

I believe you have to create a ticket with AWS support to increase `UnreservedConcurrentExecution ` as it says in the error message.

UnreservedConcurrentExecution is The maximum number of simultaneous function executions, minus the capacity reserved for individual functions. 

If you want to increase the limit go to [https://console.aws.amazon.com/support/cases#/create](https://console.aws.amazon.com/support/cases#/create)

`Service limit increase:
Case classification
Limit type: Lambda
Requests
Limit: Concurrent Requests (Expected Duration * Expected Requests per Second)`

**Comment by Sgnarf** [comment]
Is there a way to modify the code so that it reserves less instances instead of opening a ticket to AWS?
